var TSIZE_X = 48;
var TSIZE_Y = 48

var GAME_SCREEN_WIDTH_IN_TILES = 13;
var GAME_SCREEN_HEIGHT_IN_TILES = 10;

var GAME_SCREEN_WIDTH = TSIZE_X * GAME_SCREEN_WIDTH_IN_TILES;
var GAME_SCREEN_HEIGHT = TSIZE_Y * GAME_SCREEN_HEIGHT_IN_TILES;

var GAME_SCREEN_X_MIDDLE_IN_TILES = Math.floor(GAME_SCREEN_WIDTH_IN_TILES / 2);
var GAME_SCREEN_Y_MIDDLE_IN_TILES = Math.floor(GAME_SCREEN_HEIGHT_IN_TILES / 2);

Crafty.init(GAME_SCREEN_WIDTH,GAME_SCREEN_HEIGHT, document.getElementById('game'));

Crafty.scene("Start");